name: Schemathesis Test

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: schemathesis/action@v1
        with:
          schema: 'https://example.schemathesis.io/openapi.json'
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}
          api-name: 'schemathesis-io-demo-project'
